countries = {1:"Poland", 2:"USA", 3:"Germany", 4:"France", 5:"Spain", 6:"Italy", 7:"UK", 8:"Canada", 9:"Australia", 10:"Japan"}
cities = {1:"Kraków", 2:"Hanoover", 3:"Paris", 4:"Madrid", 5:"Rome", 6:"London", 7:"Toronto", 8:"Sydney", 9:"Tokyo"}
employee_roles = {1:"Dyrektor", 2:"Nauczyciel", 3:"Tłumacz"}
languages= {1:"Polski", 2:"Angielski", 3: "Niemiecki"}
module_types = {1: "Stationary", 2:"Asynchronous", 3: "Synchronous", 4: "Hybrid"}
meeting_types = {1: "Stationary", 2:"Asynchronous", 3: "Synchronous"}
topics = {
    1: "Artificial Intelligence",
    2: "Machine Learning",
    3: "Blockchain Technology",
    4: "Cybersecurity",
    5: "Quantum Computing",
    6: "Cloud Computing",
    7: "Internet of Things (IoT)",
    8: "Augmented Reality (AR)",
    9: "Virtual Reality (VR)",
    10: "Big Data Analytics",
    # 11: "5G Technology",
    # 12: "Web Development",
    # 13: "Mobile App Development",
    # 14: "DevOps Practices",
    # 15: "Software Testing and Automation",
    # 16: "Natural Language Processing (NLP)",
    # 17: "Computer Vision",
    # 18: "Edge Computing",
    # 19: "Cryptocurrency and Digital Assets",
    # 20: "Robotics and Automation"
}
event_tyes = {1: "Webinar", 2: "Course", 3: "Study", 4: "Study Module"}
START_DATE_ALL = "2021-10-10"



webinar_titles_and_descriptions = [
    ("Mastering Agile Project Management", "Learn the principles of Agile to enhance team productivity and project delivery."),
    ("AI in Business: Transforming the Future", "Explore how artificial intelligence is reshaping industries and driving innovation."),
    ("Cybersecurity Essentials for Modern Enterprises", "Understand key strategies to protect your business from cyber threats."),
    ("Cloud Computing: Benefits and Best Practices", "Dive into cloud technology and learn how to optimize its use for your business."),
    ("The Power of Data Analytics", "Unlock the potential of data to drive informed decision-making."),
    ("Blockchain for Business Leaders", "Discover practical applications of blockchain technology in various industries."),
    ("Digital Marketing Strategies for 2024", "Stay ahead with cutting-edge marketing techniques and tools."),
    ("Scaling Startups: Challenges and Solutions", "Gain insights into scaling your business effectively."),
    ("Remote Work: Tools and Tactics for Success", "Learn how to manage and thrive in a remote work environment."),
    ("Effective Leadership in the Tech Industry", "Develop leadership skills tailored for the fast-paced tech sector."),
    ("Building High-Performance Teams", "Explore techniques for creating cohesive and motivated teams."),
    ("DevOps Fundamentals for Beginners", "Understand the basics of DevOps and its impact on software development."),
    ("UX/UI Design Trends for Modern Applications", "Stay updated with the latest trends in user experience and interface design."),
    ("Navigating Regulatory Compliance in Tech", "Learn how to manage compliance challenges in the technology sector."),
    ("Introduction to Internet of Things (IoT)", "Discover the potential of IoT and its applications in business."),
    ("The Future of FinTech", "Explore innovations driving the financial technology industry."),
    ("Cybersecurity for Startups", "Essential tips for protecting your emerging business from cyber attacks."),
    ("Harnessing Machine Learning in Business", "Understand how machine learning can solve real-world problems."),
    ("Building Scalable Web Applications", "Learn techniques for developing robust and scalable web apps."),
    ("The Art of Negotiation for Tech Professionals", "Master negotiation skills to close deals and build partnerships."),
    ("AI-Powered Marketing: Tools and Techniques", "Discover how AI is revolutionizing marketing strategies."),
    ("Optimizing Business Processes with RPA", "Learn how robotic process automation can streamline operations."),
    ("Introduction to Kubernetes", "Get started with Kubernetes and container orchestration."),
    ("The Role of Leadership in Digital Transformation", "Explore how leaders can guide their organizations through technological change."),
    ("Data Privacy Regulations and Compliance", "Understand global data privacy laws and how they impact businesses."),
    ("Developing a Winning Product Roadmap", "Learn how to align product development with business goals."),
    ("Tech-Driven Customer Engagement", "Explore tools and methods for enhancing customer interactions."),
    ("Overcoming Challenges in E-commerce", "Practical tips for succeeding in the competitive e-commerce landscape."),
    ("Introduction to No-Code Platforms", "Learn how to build applications without traditional coding."),
    ("Harnessing Big Data for Competitive Advantage", "Strategies for leveraging big data in your industry."),
    ("Financial Modeling for Tech Startups", "Understand the financial aspects of running and scaling a startup."),
    ("Integrating AI into Existing Business Models", "Learn practical steps to incorporate AI into your operations."),
    ("The Rise of Edge Computing", "Explore how edge computing is transforming data processing."),
    ("Embracing Diversity in Tech Teams", "Understand the importance of diversity for innovation and success."),
    ("SEO Best Practices for Tech Companies", "Optimize your website to rank higher in search engine results."),
    ("Creating a Culture of Innovation", "Learn how to foster an environment that encourages creativity and experimentation."),
    ("SaaS Metrics Every Founder Should Know", "Key performance indicators to track for your SaaS business."),
    ("Streamlining Operations with Cloud ERP", "Discover the benefits of implementing a cloud-based ERP system."),
    ("Digital Payment Trends and Insights", "Stay informed on the latest developments in digital payment solutions."),
    ("Developing Resilient Supply Chains", "Tech strategies for ensuring supply chain continuity."),
    ("Building Brand Loyalty Through Technology", "Learn how tech solutions can enhance customer retention."),
    ("The Ethics of AI", "Discuss the ethical considerations of implementing AI in your business."),
    ("Agile vs. Waterfall: Choosing the Right Approach", "Compare project management methodologies to find the best fit."),
    ("Tech Tools for HR Management", "Discover software solutions to streamline HR processes."),
    ("Introduction to Quantum Computing", "Explore the basics of quantum computing and its potential impact."),
    ("From Idea to MVP: Building Startups", "Learn the steps to transform a concept into a minimum viable product."),
    ("Sustainable Technology Practices", "Explore how to integrate eco-friendly solutions into your tech strategy."),
    ("Cybersecurity Threats in 2024", "Understand emerging threats and how to mitigate them."),
    ("The Future of Work: Trends and Predictions", "Examine how technology is reshaping the workplace."),
    ("Using AI for Predictive Analytics", "Harness AI to predict trends and improve decision-making."),
    ("Enhancing Customer Experience with Chatbots", "Implement chatbot technology to improve customer service."),
    ("Building Resilient IT Infrastructure", "Learn strategies to ensure business continuity through robust IT setups."),
    ("Effective Networking in Tech", "Tips for building meaningful professional relationships."),
    ("Monetizing APIs", "Explore ways to turn your APIs into revenue streams."),
    ("Introduction to Ethical Hacking", "Learn the basics of ethical hacking to secure your systems."),
    ("Cloud Security: Best Practices", "Understand how to protect data and applications in the cloud."),
    ("Digital Transformation in Healthcare", "Discover how technology is revolutionizing the healthcare sector."),
    ("Launching a Successful Crowdfunding Campaign", "Learn tips for creating and promoting a crowdfunding initiative."),
    ("The Power of Open Source Software", "Explore the benefits and challenges of adopting open-source solutions."),
    ("Data Visualization for Decision Makers", "Learn tools and techniques to present data effectively."),
    ("The Role of Technology in Sustainability", "How businesses can leverage tech for eco-friendly practices."),
    ("Introduction to Natural Language Processing", "Understand NLP and its applications in the tech industry."),
    ("Women in Tech: Breaking Barriers", "Celebrate and learn from the success stories of women in technology."),
    ("Augmented Reality in Marketing", "Explore how AR can create engaging marketing campaigns."),
    ("Personal Branding for Tech Professionals", "Tips to establish a strong professional presence online."),
    ("Accelerating Innovation with Hackathons", "Learn how to organize or participate in hackathons to foster innovation."),
    ("AI-Powered Personalization in Retail", "Explore how AI can tailor customer experiences in retail."),
    ("Introduction to Cybersecurity Certifications", "A guide to certifications that can boost your career."),
    ("The Future of Mobile App Development", "Trends and technologies shaping the mobile app landscape."),
    ("Overcoming the Digital Skills Gap", "Strategies for upskilling your workforce in a tech-driven world."),
    ("Hybrid Cloud Strategies", "Learn the benefits and challenges of hybrid cloud implementations."),
    ("Introduction to Cryptocurrency", "Understand the basics of cryptocurrencies and blockchain."),
    ("Driving Growth with Social Media Analytics", "Learn how to use analytics to refine your social media strategy."),
    ("The Role of VR in Employee Training", "Explore how virtual reality can enhance corporate training programs."),
    ("Smart Cities: Innovations and Opportunities", "Discover how technology is creating smarter, more connected cities."),
    ("Data-Driven Marketing Campaigns", "Leverage data to design and execute successful marketing campaigns."),
    ("The Importance of Accessibility in Tech", "Learn how to create inclusive products and services."),
    ("Integrating APIs for Seamless Operations", "Discover how APIs can streamline workflows and enhance connectivity."),
    ("Leadership in Crisis: Tech Solutions", "Explore how technology can aid leadership during challenging times."),
    ("IoT Security Challenges and Solutions", "Understand the risks associated with IoT devices and how to mitigate them."),
    ("The Evolution of Digital Advertising", "Stay updated with the latest trends in digital ad technologies."),
    ("Leveraging Tech for Nonprofit Growth", "Explore how technology can support nonprofit missions."),
    ("Remote Team Building Strategies", "Learn how to create strong, cohesive teams in a remote setting."),
    ("Implementing Blockchain in Supply Chains", "Discover the benefits of blockchain technology for supply chain transparency."),
    ("Gamification in Business", "Learn how gamification can drive engagement and productivity."),
    ("Preparing for a Career in AI", "Steps to start and succeed in the field of artificial intelligence."),
    ("Understanding the Metaverse", "Explore the concept of the metaverse and its business implications."),
    ("Breaking into Tech as a Non-Coder", "Discover pathways to thrive in the tech industry without coding skills."),
    ("Maximizing ROI with Martech Tools", "Learn how to choose and use marketing technology for maximum impact."),
    ("The Role of Analytics in Financial Planning", "Explore how analytics can support better financial decision-making."),
    ("Tech for Good: Driving Social Impact", "Examples of how technology is being used to address societal challenges."),
    ("Enhancing Collaboration with Digital Tools", "Explore the best tools to improve team collaboration."),
    ("Strategic Roadmaps for IT Modernization", "Learn how to plan and execute IT upgrades effectively."),
    ("Overcoming Cloud Migration Challenges", "Tips and strategies to ensure a smooth transition to the cloud."),
    ("AI Ethics and Fairness", "Delve into ethical considerations for developing and deploying AI systems."),
]



