reader: markdown+hard_line_breaks
writer: latex
toc: true
toc-depth: 1
number-sections: true
pdf-engine: pdflatex
variables:
  classoption: a4paper
  geometry:
    - width=14cm
  fontsize: 12pt
  mainfont: Noto Sans
  mainfontoptions:
    - BoldFont={Noto Sans Medium}
  monofont: Noto Mono
  monofontoptions: Scale=0.9
  hyperrefoptions:
    - pdfpagemode=UseNone
  colorlinks: true
  link-citations: true
  header-includes:
    \AtBeginEnvironment{longtable}{\footnotesize}
output:
  pdf_document:
    includes:
      in_header: "latex_pandoc_preamble.tex"